"""add email verification fields to artist_submissions

Revision ID: 0ea627154f98
Revises: e13c0fa0d741
Create Date: 2026-01-30 11:17:52.757536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ea627154f98'
down_revision: Union[str, Sequence[str], None] = 'e13c0fa0d741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_logs_id'), table_name='search_logs')
    op.drop_table('search_logs')
    op.add_column('artist_submissions', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('artist_submissions', sa.Column('verify_token_hash', sa.String(length=128), nullable=False))
    op.add_column('artist_submissions', sa.Column('verify_token_expires_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('artist_submissions', 'zip_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('artist_submissions', 'neighborhood',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('artist_submissions', 'genre',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('artists', 'zip_code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=5),
               existing_nullable=False)
    op.alter_column('artists', 'neighborhood',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'neighborhood',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('artists', 'zip_code',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('artist_submissions', 'genre',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('artist_submissions', 'neighborhood',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('artist_submissions', 'zip_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_column('artist_submissions', 'verify_token_expires_at')
    op.drop_column('artist_submissions', 'verify_token_hash')
    op.drop_column('artist_submissions', 'email_verified_at')
    op.create_table('search_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('stage_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('neighborhood', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('min_listeners', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_listeners', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('page', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('limit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('search_logs_pkey'))
    )
    op.create_index(op.f('ix_search_logs_id'), 'search_logs', ['id'], unique=False)
    # ### end Alembic commands ###
