"""add moderation fields to artist_submissions

Revision ID: 54deaafcce7e
Revises: 0ea627154f98
Create Date: 2026-01-30 13:52:55.870581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54deaafcce7e'
down_revision: Union[str, Sequence[str], None] = '0ea627154f98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_logs_id'), table_name='search_logs')
    op.drop_table('search_logs')
    op.add_column('artist_submissions', sa.Column('approved_artist_id', sa.Integer(), nullable=True))
    op.add_column('artist_submissions', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('artist_submissions', sa.Column('review_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist_submissions', 'review_notes')
    op.drop_column('artist_submissions', 'reviewed_at')
    op.drop_column('artist_submissions', 'approved_artist_id')
    op.create_table('search_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('stage_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('neighborhood', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('min_listeners', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_listeners', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('page', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('limit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('search_logs_pkey'))
    )
    op.create_index(op.f('ix_search_logs_id'), 'search_logs', ['id'], unique=False)
    # ### end Alembic commands ###
