"""updating alembic schema with new database model

Revision ID: 78e7bad1950d
Revises: d4e8b2f1a9c3
Create Date: 2026-05-29 12:32:01.088442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78e7bad1950d'
down_revision: Union[str, Sequence[str], None] = 'd4e8b2f1a9c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='submission_status'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitter_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('honeypot', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('stage_name', sa.String(length=200), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('neighborhood', sa.String(length=50), nullable=True),
    sa.Column('genre', sa.String(length=80), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verify_token_hash', sa.String(length=128), nullable=False),
    sa.Column('verify_token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_artist_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('spotify_url', sa.Text(), nullable=True),
    sa.Column('youtube_url', sa.Text(), nullable=True),
    sa.Column('instagram_url', sa.Text(), nullable=True),
    sa.Column('soundcloud_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artist_submissions_id'), 'artist_submissions', ['id'], unique=False)
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('stage_name', sa.String(length=50), nullable=False),
    sa.Column('zip_code', sa.String(length=5), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('neighborhood', sa.String(length=50), nullable=True),
    sa.Column('genre', sa.String(length=50), nullable=False),
    sa.Column('monthly_listeners', sa.Integer(), nullable=True),
    sa.Column('spotify_url', sa.Text(), nullable=True),
    sa.Column('youtube_url', sa.Text(), nullable=True),
    sa.Column('soundcloud_url', sa.Text(), nullable=True),
    sa.Column('instagram_url', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('edit_token_hash', sa.String(length=128), nullable=True),
    sa.Column('edit_token_expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('spotify_followers_updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_genre', 'artists', ['genre'], unique=False)
    op.create_index('idx_listeners', 'artists', ['monthly_listeners'], unique=False)
    op.create_index('idx_zip', 'artists', ['zip_code'], unique=False)
    op.create_index(op.f('ix_artists_id'), 'artists', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artists_id'), table_name='artists')
    op.drop_index('idx_zip', table_name='artists')
    op.drop_index('idx_listeners', table_name='artists')
    op.drop_index('idx_genre', table_name='artists')
    op.drop_table('artists')
    op.drop_index(op.f('ix_artist_submissions_id'), table_name='artist_submissions')
    op.drop_table('artist_submissions')
    # ### end Alembic commands ###
