"""modify artist_submissions table

Revision ID: e13c0fa0d741
Revises: e82c3590d881
Create Date: 2026-01-29 16:12:31.825135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e13c0fa0d741'
down_revision: Union[str, Sequence[str], None] = 'e82c3590d881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_logs_id'), table_name='search_logs')
    op.drop_table('search_logs')
    op.alter_column('artist_submissions', 'zip_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('artist_submissions', 'neighborhood',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('artist_submissions', 'genre',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('artists', 'neighborhood',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'neighborhood',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('artist_submissions', 'genre',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('artist_submissions', 'neighborhood',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('artist_submissions', 'zip_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.create_table('search_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('stage_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('neighborhood', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('min_listeners', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_listeners', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('page', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('limit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('search_logs_pkey'))
    )
    op.create_index(op.f('ix_search_logs_id'), 'search_logs', ['id'], unique=False)
    # ### end Alembic commands ###
