"""add latitude and longitude to artists

Revision ID: eb5a200e0216
Revises: fb4e562a7404
Create Date: 2026-01-24 12:08:47.791803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb5a200e0216'
down_revision: Union[str, Sequence[str], None] = 'fb4e562a7404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('latitude', sa.DOUBLE_PRECISION(), nullable=True))
    op.add_column('artists', sa.Column('longitude', sa.DOUBLE_PRECISION(), nullable=True))
    op.create_index(
    "ix_artists_lat_lon",
    "artists",
    ["latitude", "longitude"]
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'longitude')
    op.drop_column('artists', 'latitude')
    # ### end Alembic commands ###
