"""baseline

Revision ID: fb4e562a7404
Revises: 
Create Date: 2026-01-23 19:29:56.794896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb4e562a7404'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('stage_name', sa.String(length=50), nullable=False),
    sa.Column('zip_code', sa.String(length=50), nullable=False),
    sa.Column('neighborhood', sa.String(length=50), nullable=False),
    sa.Column('genre', sa.String(length=50), nullable=False),
    sa.Column('monthly_listeners', sa.Integer(), nullable=True),
    sa.Column('spotify_url', sa.Text(), nullable=True),
    sa.Column('youtube_url', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_genre', 'artists', ['genre'], unique=False)
    op.create_index('idx_listeners', 'artists', ['monthly_listeners'], unique=False)
    op.create_index('idx_zip', 'artists', ['zip_code'], unique=False)
    op.create_index(op.f('ix_artists_id'), 'artists', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artists_id'), table_name='artists')
    op.drop_index('idx_zip', table_name='artists')
    op.drop_index('idx_listeners', table_name='artists')
    op.drop_index('idx_genre', table_name='artists')
    op.drop_table('artists')
    # ### end Alembic commands ###
